version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: disk_bot_core_node:latest
    deploy:
      replicas: 1
    #depends_on:
    #ports:
    env_file:
      - credentials.env
    restart: always
    environment:
      TZ: 'America/Edmonton'
    #links:
    networks:
      - disk_backend
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - ./out:/usr/src/app/out
    ports:
      - 8069:8069

  mdb:
    image: mongo:focal
    restart: always
    ports:
      - 22017:27017
    volumes:
      - mdb-data:/data/db
    networks:
      - disk_backend 

networks:
  disk_backend:
volumes:
  mdb-data:
